AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Devl ECR Registry"
Parameters:
  env:
    Type: String
    Description: Deployment Environment
    Default: "devl"
  
  awsAcct:
    Type: String
    Description: "AWS Account Number"
    Default: "600831013510"

  repoName:
    Type: String
    Description: Name for ecr repo
    Default: "collibradq-ecr-registry"

  componentValue:
    Type: String
    Default: "ecr-collibra-dq"



Resources:

  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "key for dq ECR"
      EnableKeyRotation: True
      KeyPolicy:
        Version: "2012-10-17"
        Id: "default"
        Statement:
          - Sid: "Key Owner" # root access
            Effect: "Allow"
            Principal:
              "AWS": !Join [":", ["arn:aws:iam:" , !Ref awsAcct , "root"]]
            Action: "kms:*"
            Resource: "*"
      Tags:
        - Key: "Name"
          Value: !Join [ "-", [ !Ref env , "dq-ecr-key" ] ]
        - Key: "component"
          Value: !Ref componentValue

  KeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Join [ "", [ "alias/" , !Ref env , "-dq-ecr-key" ] ]
      TargetKeyId:
        !Ref KMSKey            

  ecrRepo:
    Type: AWS::ECR::Repository
    DependsOn:
      - KMSKey
      - KeyAlias

    Properties: 
      RepositoryName: !Sub ${repoName}-repo
      ImageScanningConfiguration: 
        ScanOnPush: true
      ImageTagMutability: "IMMUTABLE"
      EncryptionConfiguration:     
          EncryptionType: "KMS"
          KmsKey: !Ref KeyAlias
      
      Tags:
        - Key: "Name"
          Value: !Join [ "-", [ !Ref env , "dq-ecr-repo" ] ]
        - Key: "component"
          Value: !Ref componentValue







     

      
      
      